version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=assembleia
      - MYSQL_ROOT_PASSWORD=umasenhafacil
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 #equivalente a true
      - TZ=America/Belem
    command: ['--default-time-zone=-03:00']
    #volumes:
    #  - ".db:/docker-entrypoint-initdb.d"
    ports:
      - "3307:3306"