
GET  http://localhost:3000/pautas HTTP/1.1

###

POST http://localhost:3000/pautas HTTP/1.1
Content-Type: application/json

{
  "descricao": "primeira pauta"
}

###

POST http://localhost:3000/pautas/1/sessao HTTP/1.1
Content-Type: application/json

{
  "minutos": "1"
}